export enum ErrorCode {
  STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND",
  PARENT_NOT_FOUND = "PARENT_NOT_FOUND",
  MENU_ITEM_NOT_FOUND = "MENU_ITEM_NOT_FOUND",
  ITEM_UNAVAILABLE = "ITEM_UNAVAILABLE",
  ALLERGEN_CONFLICT = "ALLERGEN_CONFLICT",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
}